In [1]:
import numpy
from numpy import linalg

from sympy.solvers import solve
from sympy import Symbol, Eq

In [13]:
def quad(a,b,c,d,x,jop,jhop):
    while True:
        print("IT")
        n = len(x)
        m = len(a)
        aop = a[:, jop]
        naop = linalg.inv(aop)
        njop = set(range(n)) - set(jop)

        fc = (c.T + x.T * d).T
        fu = (- fc[jop].T * naop).T
        fd = (fu.T * a + fc.T).T
        print(fd)

        if (fd >= -0.0000001).all():
            return x

        j0 = 0
        while fd[j0] >= 0:
            j0 += 1
            print("adsasd")

        l = numpy.array([0] * n, dtype=numpy.float64)
        for j in njop:
            if j == j0:
                l[j] = 1
            else:
                l[j] = 0

        hul = d[:, jhop][jhop, :]
        hdl = a[:, jhop]
        hl = numpy.concatenate((hul, hdl))
        
        hur = a[:, jhop].T
        hz = numpy.matrix(numpy.zeros((len(hl) - len(hur), hur.shape[1]), dtype=numpy.float64))
        hr = numpy.concatenate((hur, hz))
    
        h = numpy.concatenate((hl, hr), 1)
        nh = linalg.inv(h)     

        bs = a[:,j0]
        badd = d[jhop, :][:, j0]
        bs = - numpy.concatenate((badd, bs))
        xy = nh * bs
        l[jhop] = xy[ :len(jhop), :].transpose()
        l = numpy.matrix(l).T
        et = l.T * d * l
        qj0 = numpy.Infinity if et == 0 else abs(fd[j0]) / et


        q0 = qj0
        js = j0
        for j in jhop:
            q = numpy.Infinity if l[j] >= 0 else - x[j] / l[j]
            if q < q0:
                q0 = q
                js = j

        if q0 == numpy.Infinity:
            print('Неограниченно снизу')
            return None

        x = x + q0[0,0] * l

        if j0 == js:
            jhop.append(js)
            continue

        if js in jhop and js not in jop:
            jhop.remove(js)
            continue

        s = jop.index(js)
        jp = None
        for j in set(jhop) - set(jop):
            if (naop * a[:, jp])[s] != 0:
                jp = j

        if jp is not None:
            jop[s] = jp
            jhop.remove(js)
        else:
            jop[jop.index(js)] = j0
            jhop[jhop.index(js)] = j0

In [14]:
a = numpy.matrix([
    [1, 0, 2, 1],
    [0, 1, -1, 2],
], dtype=numpy.float64)

b = numpy.matrix([
    [2],
    [2],
], dtype=numpy.float64)

c = numpy.matrix([
    [-8],
    [-6],
    [-4],
    [-6],
], dtype=numpy.float64)

d = numpy.matrix([
    [2, 1, 1, 0],
    [1, 1, 0, 0],
    [1, 0, 1, 0],
    [0, 0, 0, 0],
], dtype=numpy.float64)

x = numpy.matrix([
    [2],
    [3],
    [0],
    [0]
], dtype=numpy.float64)

jop = [0, 1]
jhop = [0, 1]

quad(a, b, c, d, x, jop, jhop)

IT
[[ 0.]
 [ 0.]
 [-1.]
 [-3.]]
adsasd
adsasd
IT
[[ 0.]
 [ 0.]
 [ 0.]
 [-1.]]
adsasd
adsasd
adsasd
IT
[[ 0. ]
 [ 0. ]
 [ 0. ]
 [-0.5]]
adsasd
adsasd
adsasd
IT
[[  0.00000000e+00]
 [  0.00000000e+00]
 [  2.00000000e-01]
 [  8.88178420e-16]]


matrix([[ 1.7],
        [ 2.4],
        [ 0. ],
        [ 0.3]])

In [15]:
a = numpy.matrix([
    [1, 2, 0, 1, 0, 4, -1, -3],
    [1, 3, 0, 0, 1, -1, -1, -2],
    [1, 4, 1, 0, 0, 2, -2, 0]
], dtype=numpy.float64)

x = numpy.matrix([
    [0],
    [0],
    [6],
    [4],
    [5],
    [0],
    [0],
    [0]
], dtype=numpy.float64)
b = numpy.matrix([
    [4],
    [5],
    [6]
], dtype=numpy.float64)
c = numpy.matrix([
    [-10],
    [-31],
    [7],
    [0],
    [-21],
    [-16],
    [11],
    [-7]
], dtype=numpy.float64)
d = numpy.matrix([
    [6, 11, -1, 0, 6, -7, -3, -2],
    [11, 41, -1, 0, 7, -24, 0, -3],
    [-1, -1, 1, 0, -3, -4, 2, -1],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [6, 7, -3, 0, 11, 6, -7, 1],
    [-7, -24, -4, 0, 6, 42, -7, 10],
    [-3, 0, 2, 0, -7, -7, 5, 1],
    [-2, -3, -1, 0, 1, 10, -1, 3]
], dtype=numpy.float64)

jop = [2, 3, 4]
jhop = [2, 3, 4]

quad(a, b, c, d, x, jop, jhop)

IT
[[  0.]
 [-42.]
 [  0.]
 [  0.]
 [  0.]
 [ 10.]
 [  0.]
 [ 24.]]
adsasd
IT
[[  5.88]
 [  0.  ]
 [  0.  ]
 [  0.  ]
 [  0.  ]
 [-30.32]
 [  5.88]
 [ -1.2 ]]
adsasd
adsasd
adsasd
adsasd
adsasd


ValueError: shapes (3,3) and (3,1,8) not aligned: 3 (dim 1) != 1 (dim 1)

In [16]:
numpy.matrix

numpy.matrixlib.defmatrix.matrix

In [24]:
a = numpy.matrix([
    [1, 1, 1, 2, 3, 1, 1, -2],
    [0, 1, 0, 1, 1, 2, 3, -4],
    [0, 1, 1, 3, -1, 2, 4, -5]
], dtype=numpy.float64)

x = numpy.matrix([
    [3],
    [4],
    [1],
    [0],
    [0],
    [0],
    [0],
    [0]
], dtype=numpy.float64)
b = numpy.matrix([
    [8],
    [4],
    [5]
], dtype=numpy.float64)
B = numpy.matrix([
    [1, 1, 0, 3, -3, 1, 1, 1],
    [-1, 1, 1, 2, -1, 0, 1, 1]
])

aa = numpy.matrix([[5],[4]])
c = -aa.T * B
print(c)
d = B.T * B
jop = [0, 1, 2]
jhop = [0, 1, 2]

quad(a, b, c, d, x, jop, jhop)

[[ -1  -9  -4 -23  19  -5  -9  -9]]
IT
[[  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [ 18.  26.  21.  40.  -2.  22.  26.  26.]
 [-46. -30. -40.  -2. -86. -38. -30. -30.]
 [ -6.  -6.  -6.  -6.  -6.  -6.  -6.  -6.]
 [ -5.  -5.  -5.  -5.  -5.  -5.  -5.  -5.]
 [ 29.   5.  20. -37.  89.  17.   5.   5.]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()